// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package main;

public final class Request {
    private Request() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface RequestEchoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RequestEcho)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string echoMsg = 1;</code>
         */
        boolean hasEchoMsg();
        /**
         * <code>optional string echoMsg = 1;</code>
         */
        java.lang.String getEchoMsg();
        /**
         * <code>optional string echoMsg = 1;</code>
         */
        com.google.protobuf.ByteString
        getEchoMsgBytes();
    }
    /**
     * Protobuf type {@code RequestEcho}
     */
    public static final class RequestEcho extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:RequestEcho)
            RequestEchoOrBuilder {
        // Use RequestEcho.newBuilder() to construct.
        private RequestEcho(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private RequestEcho(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final RequestEcho defaultInstance;
        public static RequestEcho getDefaultInstance() {
            return defaultInstance;
        }

        public RequestEcho getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private RequestEcho(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            echoMsg_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return main.Request.internal_static_RequestEcho_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return main.Request.internal_static_RequestEcho_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            main.Request.RequestEcho.class, main.Request.RequestEcho.Builder.class);
        }

        public static com.google.protobuf.Parser<RequestEcho> PARSER =
                new com.google.protobuf.AbstractParser<RequestEcho>() {
                    public RequestEcho parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new RequestEcho(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<RequestEcho> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int ECHOMSG_FIELD_NUMBER = 1;
        private java.lang.Object echoMsg_;
        /**
         * <code>optional string echoMsg = 1;</code>
         */
        public boolean hasEchoMsg() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string echoMsg = 1;</code>
         */
        public java.lang.String getEchoMsg() {
            java.lang.Object ref = echoMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    echoMsg_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string echoMsg = 1;</code>
         */
        public com.google.protobuf.ByteString
        getEchoMsgBytes() {
            java.lang.Object ref = echoMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                echoMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            echoMsg_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getEchoMsgBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getEchoMsgBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static main.Request.RequestEcho parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static main.Request.RequestEcho parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static main.Request.RequestEcho parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static main.Request.RequestEcho parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static main.Request.RequestEcho parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static main.Request.RequestEcho parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static main.Request.RequestEcho parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static main.Request.RequestEcho parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static main.Request.RequestEcho parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static main.Request.RequestEcho parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(main.Request.RequestEcho prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code RequestEcho}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RequestEcho)
                main.Request.RequestEchoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return main.Request.internal_static_RequestEcho_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return main.Request.internal_static_RequestEcho_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                main.Request.RequestEcho.class, main.Request.RequestEcho.Builder.class);
            }

            // Construct using main.Request.RequestEcho.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                echoMsg_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return main.Request.internal_static_RequestEcho_descriptor;
            }

            public main.Request.RequestEcho getDefaultInstanceForType() {
                return main.Request.RequestEcho.getDefaultInstance();
            }

            public main.Request.RequestEcho build() {
                main.Request.RequestEcho result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public main.Request.RequestEcho buildPartial() {
                main.Request.RequestEcho result = new main.Request.RequestEcho(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.echoMsg_ = echoMsg_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof main.Request.RequestEcho) {
                    return mergeFrom((main.Request.RequestEcho)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(main.Request.RequestEcho other) {
                if (other == main.Request.RequestEcho.getDefaultInstance()) return this;
                if (other.hasEchoMsg()) {
                    bitField0_ |= 0x00000001;
                    echoMsg_ = other.echoMsg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                main.Request.RequestEcho parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (main.Request.RequestEcho) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object echoMsg_ = "";
            /**
             * <code>optional string echoMsg = 1;</code>
             */
            public boolean hasEchoMsg() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional string echoMsg = 1;</code>
             */
            public java.lang.String getEchoMsg() {
                java.lang.Object ref = echoMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        echoMsg_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string echoMsg = 1;</code>
             */
            public com.google.protobuf.ByteString
            getEchoMsgBytes() {
                java.lang.Object ref = echoMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    echoMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string echoMsg = 1;</code>
             */
            public Builder setEchoMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                echoMsg_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string echoMsg = 1;</code>
             */
            public Builder clearEchoMsg() {
                bitField0_ = (bitField0_ & ~0x00000001);
                echoMsg_ = getDefaultInstance().getEchoMsg();
                onChanged();
                return this;
            }
            /**
             * <code>optional string echoMsg = 1;</code>
             */
            public Builder setEchoMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                echoMsg_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:RequestEcho)
        }

        static {
            defaultInstance = new RequestEcho(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:RequestEcho)
    }

    public interface RPcOkOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RPcOk)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string RPcMsg = 1;</code>
         */
        boolean hasRPcMsg();
        /**
         * <code>optional string RPcMsg = 1;</code>
         */
        java.lang.String getRPcMsg();
        /**
         * <code>optional string RPcMsg = 1;</code>
         */
        com.google.protobuf.ByteString
        getRPcMsgBytes();
    }
    /**
     * Protobuf type {@code RPcOk}
     */
    public static final class RPcOk extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:RPcOk)
            RPcOkOrBuilder {
        // Use RPcOk.newBuilder() to construct.
        private RPcOk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private RPcOk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final RPcOk defaultInstance;
        public static RPcOk getDefaultInstance() {
            return defaultInstance;
        }

        public RPcOk getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private RPcOk(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            rPcMsg_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return main.Request.internal_static_RPcOk_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return main.Request.internal_static_RPcOk_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            main.Request.RPcOk.class, main.Request.RPcOk.Builder.class);
        }

        public static com.google.protobuf.Parser<RPcOk> PARSER =
                new com.google.protobuf.AbstractParser<RPcOk>() {
                    public RPcOk parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new RPcOk(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<RPcOk> getParserForType() {
            return PARSER;
        }

        public interface responseOrBuilder extends
                // @@protoc_insertion_point(interface_extends:RPcOk.response)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>optional string responseMsg = 2;</code>
             */
            boolean hasResponseMsg();
            /**
             * <code>optional string responseMsg = 2;</code>
             */
            java.lang.String getResponseMsg();
            /**
             * <code>optional string responseMsg = 2;</code>
             */
            com.google.protobuf.ByteString
            getResponseMsgBytes();
        }
        /**
         * Protobuf type {@code RPcOk.response}
         */
        public static final class response extends
                com.google.protobuf.GeneratedMessage implements
                // @@protoc_insertion_point(message_implements:RPcOk.response)
                responseOrBuilder {
            // Use response.newBuilder() to construct.
            private response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }
            private response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

            private static final response defaultInstance;
            public static response getDefaultInstance() {
                return defaultInstance;
            }

            public response getDefaultInstanceForType() {
                return defaultInstance;
            }

            private final com.google.protobuf.UnknownFieldSet unknownFields;
            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }
            private response(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 18: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000001;
                                responseMsg_ = bs;
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return main.Request.internal_static_RPcOk_response_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return main.Request.internal_static_RPcOk_response_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                main.Request.RPcOk.response.class, main.Request.RPcOk.response.Builder.class);
            }

            public static com.google.protobuf.Parser<response> PARSER =
                    new com.google.protobuf.AbstractParser<response>() {
                        public response parsePartialFrom(
                                com.google.protobuf.CodedInputStream input,
                                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                throws com.google.protobuf.InvalidProtocolBufferException {
                            return new response(input, extensionRegistry);
                        }
                    };

            @java.lang.Override
            public com.google.protobuf.Parser<response> getParserForType() {
                return PARSER;
            }

            private int bitField0_;
            public static final int RESPONSEMSG_FIELD_NUMBER = 2;
            private java.lang.Object responseMsg_;
            /**
             * <code>optional string responseMsg = 2;</code>
             */
            public boolean hasResponseMsg() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional string responseMsg = 2;</code>
             */
            public java.lang.String getResponseMsg() {
                java.lang.Object ref = responseMsg_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        responseMsg_ = s;
                    }
                    return s;
                }
            }
            /**
             * <code>optional string responseMsg = 2;</code>
             */
            public com.google.protobuf.ByteString
            getResponseMsgBytes() {
                java.lang.Object ref = responseMsg_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    responseMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            private void initFields() {
                responseMsg_ = "";
            }
            private byte memoizedIsInitialized = -1;
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeBytes(2, getResponseMsgBytes());
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;
            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1) return size;

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(2, getResponseMsgBytes());
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;
            @java.lang.Override
            protected java.lang.Object writeReplace()
                    throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static main.Request.RPcOk.response parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static main.Request.RPcOk.response parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static main.Request.RPcOk.response parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            public static main.Request.RPcOk.response parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            public static main.Request.RPcOk.response parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }
            public static main.Request.RPcOk.response parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }
            public static main.Request.RPcOk.response parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }
            public static main.Request.RPcOk.response parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }
            public static main.Request.RPcOk.response parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return PARSER.parseFrom(input);
            }
            public static main.Request.RPcOk.response parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }

            public static Builder newBuilder() { return Builder.create(); }
            public Builder newBuilderForType() { return newBuilder(); }
            public static Builder newBuilder(main.Request.RPcOk.response prototype) {
                return newBuilder().mergeFrom(prototype);
            }
            public Builder toBuilder() { return newBuilder(this); }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }
            /**
             * Protobuf type {@code RPcOk.response}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:RPcOk.response)
                    main.Request.RPcOk.responseOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return main.Request.internal_static_RPcOk_response_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return main.Request.internal_static_RPcOk_response_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    main.Request.RPcOk.response.class, main.Request.RPcOk.response.Builder.class);
                }

                // Construct using main.Request.RPcOk.response.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }
                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }
                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    responseMsg_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return main.Request.internal_static_RPcOk_response_descriptor;
                }

                public main.Request.RPcOk.response getDefaultInstanceForType() {
                    return main.Request.RPcOk.response.getDefaultInstance();
                }

                public main.Request.RPcOk.response build() {
                    main.Request.RPcOk.response result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                public main.Request.RPcOk.response buildPartial() {
                    main.Request.RPcOk.response result = new main.Request.RPcOk.response(this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.responseMsg_ = responseMsg_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof main.Request.RPcOk.response) {
                        return mergeFrom((main.Request.RPcOk.response)other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(main.Request.RPcOk.response other) {
                    if (other == main.Request.RPcOk.response.getDefaultInstance()) return this;
                    if (other.hasResponseMsg()) {
                        bitField0_ |= 0x00000001;
                        responseMsg_ = other.responseMsg_;
                        onChanged();
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    main.Request.RPcOk.response parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (main.Request.RPcOk.response) e.getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }
                private int bitField0_;

                private java.lang.Object responseMsg_ = "";
                /**
                 * <code>optional string responseMsg = 2;</code>
                 */
                public boolean hasResponseMsg() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }
                /**
                 * <code>optional string responseMsg = 2;</code>
                 */
                public java.lang.String getResponseMsg() {
                    java.lang.Object ref = responseMsg_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            responseMsg_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                /**
                 * <code>optional string responseMsg = 2;</code>
                 */
                public com.google.protobuf.ByteString
                getResponseMsgBytes() {
                    java.lang.Object ref = responseMsg_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        responseMsg_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                /**
                 * <code>optional string responseMsg = 2;</code>
                 */
                public Builder setResponseMsg(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    responseMsg_ = value;
                    onChanged();
                    return this;
                }
                /**
                 * <code>optional string responseMsg = 2;</code>
                 */
                public Builder clearResponseMsg() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    responseMsg_ = getDefaultInstance().getResponseMsg();
                    onChanged();
                    return this;
                }
                /**
                 * <code>optional string responseMsg = 2;</code>
                 */
                public Builder setResponseMsgBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    responseMsg_ = value;
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:RPcOk.response)
            }

            static {
                defaultInstance = new response(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:RPcOk.response)
        }

        private int bitField0_;
        public static final int RPCMSG_FIELD_NUMBER = 1;
        private java.lang.Object rPcMsg_;
        /**
         * <code>optional string RPcMsg = 1;</code>
         */
        public boolean hasRPcMsg() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string RPcMsg = 1;</code>
         */
        public java.lang.String getRPcMsg() {
            java.lang.Object ref = rPcMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    rPcMsg_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string RPcMsg = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRPcMsgBytes() {
            java.lang.Object ref = rPcMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                rPcMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            rPcMsg_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getRPcMsgBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getRPcMsgBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static main.Request.RPcOk parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static main.Request.RPcOk parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static main.Request.RPcOk parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static main.Request.RPcOk parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static main.Request.RPcOk parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static main.Request.RPcOk parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static main.Request.RPcOk parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static main.Request.RPcOk parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static main.Request.RPcOk parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static main.Request.RPcOk parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(main.Request.RPcOk prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code RPcOk}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RPcOk)
                main.Request.RPcOkOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return main.Request.internal_static_RPcOk_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return main.Request.internal_static_RPcOk_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                main.Request.RPcOk.class, main.Request.RPcOk.Builder.class);
            }

            // Construct using main.Request.RPcOk.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                rPcMsg_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return main.Request.internal_static_RPcOk_descriptor;
            }

            public main.Request.RPcOk getDefaultInstanceForType() {
                return main.Request.RPcOk.getDefaultInstance();
            }

            public main.Request.RPcOk build() {
                main.Request.RPcOk result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public main.Request.RPcOk buildPartial() {
                main.Request.RPcOk result = new main.Request.RPcOk(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.rPcMsg_ = rPcMsg_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof main.Request.RPcOk) {
                    return mergeFrom((main.Request.RPcOk)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(main.Request.RPcOk other) {
                if (other == main.Request.RPcOk.getDefaultInstance()) return this;
                if (other.hasRPcMsg()) {
                    bitField0_ |= 0x00000001;
                    rPcMsg_ = other.rPcMsg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                main.Request.RPcOk parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (main.Request.RPcOk) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object rPcMsg_ = "";
            /**
             * <code>optional string RPcMsg = 1;</code>
             */
            public boolean hasRPcMsg() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional string RPcMsg = 1;</code>
             */
            public java.lang.String getRPcMsg() {
                java.lang.Object ref = rPcMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        rPcMsg_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string RPcMsg = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRPcMsgBytes() {
                java.lang.Object ref = rPcMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    rPcMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string RPcMsg = 1;</code>
             */
            public Builder setRPcMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                rPcMsg_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string RPcMsg = 1;</code>
             */
            public Builder clearRPcMsg() {
                bitField0_ = (bitField0_ & ~0x00000001);
                rPcMsg_ = getDefaultInstance().getRPcMsg();
                onChanged();
                return this;
            }
            /**
             * <code>optional string RPcMsg = 1;</code>
             */
            public Builder setRPcMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                rPcMsg_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:RPcOk)
        }

        static {
            defaultInstance = new RPcOk(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:RPcOk)
    }

    public interface RPcErrorOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RPcError)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string errorMsg = 1;</code>
         */
        boolean hasErrorMsg();
        /**
         * <code>optional string errorMsg = 1;</code>
         */
        java.lang.String getErrorMsg();
        /**
         * <code>optional string errorMsg = 1;</code>
         */
        com.google.protobuf.ByteString
        getErrorMsgBytes();
    }
    /**
     * Protobuf type {@code RPcError}
     */
    public static final class RPcError extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:RPcError)
            RPcErrorOrBuilder {
        // Use RPcError.newBuilder() to construct.
        private RPcError(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private RPcError(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final RPcError defaultInstance;
        public static RPcError getDefaultInstance() {
            return defaultInstance;
        }

        public RPcError getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private RPcError(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            errorMsg_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return main.Request.internal_static_RPcError_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return main.Request.internal_static_RPcError_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            main.Request.RPcError.class, main.Request.RPcError.Builder.class);
        }

        public static com.google.protobuf.Parser<RPcError> PARSER =
                new com.google.protobuf.AbstractParser<RPcError>() {
                    public RPcError parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new RPcError(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<RPcError> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int ERRORMSG_FIELD_NUMBER = 1;
        private java.lang.Object errorMsg_;
        /**
         * <code>optional string errorMsg = 1;</code>
         */
        public boolean hasErrorMsg() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string errorMsg = 1;</code>
         */
        public java.lang.String getErrorMsg() {
            java.lang.Object ref = errorMsg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    errorMsg_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string errorMsg = 1;</code>
         */
        public com.google.protobuf.ByteString
        getErrorMsgBytes() {
            java.lang.Object ref = errorMsg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errorMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            errorMsg_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getErrorMsgBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getErrorMsgBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static main.Request.RPcError parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static main.Request.RPcError parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static main.Request.RPcError parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static main.Request.RPcError parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static main.Request.RPcError parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static main.Request.RPcError parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static main.Request.RPcError parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static main.Request.RPcError parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static main.Request.RPcError parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static main.Request.RPcError parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(main.Request.RPcError prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code RPcError}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RPcError)
                main.Request.RPcErrorOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return main.Request.internal_static_RPcError_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return main.Request.internal_static_RPcError_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                main.Request.RPcError.class, main.Request.RPcError.Builder.class);
            }

            // Construct using main.Request.RPcError.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                errorMsg_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return main.Request.internal_static_RPcError_descriptor;
            }

            public main.Request.RPcError getDefaultInstanceForType() {
                return main.Request.RPcError.getDefaultInstance();
            }

            public main.Request.RPcError build() {
                main.Request.RPcError result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public main.Request.RPcError buildPartial() {
                main.Request.RPcError result = new main.Request.RPcError(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.errorMsg_ = errorMsg_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof main.Request.RPcError) {
                    return mergeFrom((main.Request.RPcError)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(main.Request.RPcError other) {
                if (other == main.Request.RPcError.getDefaultInstance()) return this;
                if (other.hasErrorMsg()) {
                    bitField0_ |= 0x00000001;
                    errorMsg_ = other.errorMsg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                main.Request.RPcError parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (main.Request.RPcError) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object errorMsg_ = "";
            /**
             * <code>optional string errorMsg = 1;</code>
             */
            public boolean hasErrorMsg() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional string errorMsg = 1;</code>
             */
            public java.lang.String getErrorMsg() {
                java.lang.Object ref = errorMsg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        errorMsg_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string errorMsg = 1;</code>
             */
            public com.google.protobuf.ByteString
            getErrorMsgBytes() {
                java.lang.Object ref = errorMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    errorMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string errorMsg = 1;</code>
             */
            public Builder setErrorMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                errorMsg_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string errorMsg = 1;</code>
             */
            public Builder clearErrorMsg() {
                bitField0_ = (bitField0_ & ~0x00000001);
                errorMsg_ = getDefaultInstance().getErrorMsg();
                onChanged();
                return this;
            }
            /**
             * <code>optional string errorMsg = 1;</code>
             */
            public Builder setErrorMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                errorMsg_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:RPcError)
        }

        static {
            defaultInstance = new RPcError(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:RPcError)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RequestEcho_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_RequestEcho_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RPcOk_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_RPcOk_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RPcOk_response_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_RPcOk_response_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RPcError_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_RPcError_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rrequest.proto\032\025scalapb/scalapb.proto\"\036" +
                        "\n\013RequestEcho\022\017\n\007echoMsg\030\001 \001(\t\"8\n\005RPcOk\022" +
                        "\016\n\006RPcMsg\030\001 \001(\t\032\037\n\010response\022\023\n\013responseM" +
                        "sg\030\002 \001(\t\"\034\n\010RPcError\022\020\n\010errorMsg\030\001 \001(\tB\023" +
                        "\n\021main"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                com.trueaccord.scalapb.Scalapb.getDescriptor(),
                        }, assigner);
        internal_static_RequestEcho_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_RequestEcho_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_RequestEcho_descriptor,
                new java.lang.String[] { "EchoMsg", });
        internal_static_RPcOk_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_RPcOk_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_RPcOk_descriptor,
                new java.lang.String[] { "RPcMsg", });
        internal_static_RPcOk_response_descriptor =
                internal_static_RPcOk_descriptor.getNestedTypes().get(0);
        internal_static_RPcOk_response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_RPcOk_response_descriptor,
                new java.lang.String[] { "ResponseMsg", });
        internal_static_RPcError_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_RPcError_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_RPcError_descriptor,
                new java.lang.String[] { "ErrorMsg", });
        com.trueaccord.scalapb.Scalapb.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
